[project]
name = "hyppy"
version = "1.0"
dependencies = ["numpy", "scipy", "sympy"]
requires-python = ">=3.11"
authors = [
    {name = "Joni Eronen", email = "joni.eronen@oulu.fi"},
    {name = "Perttu Hilla", email = "perttu.hilla@oulu.fi"}
]
description = "HypPy is a spin-dynamics package for Python tailored for hyperpolarization experiments."
readme = "README.md"
license = {file = "LICENSE"}

[project.optional-dependencies]
dev = ["cython", "build", "setuptools"]

[build-system]
requires = ["setuptools", "wheel", "Cython"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["hyppy*"]

[tool.setuptools.package-data]
"hyppy" = ["*.pyx", "*.pxd"]