"""
Spin-operator construction utilities for Hilbert-space calculations.

The module provides single-spin Cartesian, ladder, and spherical tensor
operators together with helpers for assembling many-spin product operators.
"""

from __future__ import annotations

from functools import lru_cache
from typing import TYPE_CHECKING

import numpy as np
import scipy.sparse as sp

from spinguin._core._la import CG_coeff, comm
from spinguin._core._parameters import parameters
from spinguin._core._utils import idx_to_lq, parse_operator_string

if TYPE_CHECKING:
    from spinguin._core._spin_system import SpinSystem


def op_E(S: float) -> np.ndarray | sp.csc_array:
    """
    Generate the unit operator for a single spin.

    Usage: ``op_E(S)``.

    Parameters
    ----------
    S : float
        Spin quantum number.

    Returns
    -------
    E : ndarray or csc_array
        Unit operator of dimension ``2*S + 1`` in the configured storage
        format.
    """

    # Determine the Hilbert-space dimension of the spin.
    dim = int(2 * S + 1)

    # Allocate the identity matrix in the requested storage format.
    if parameters.sparse_operator:
        E = sp.eye_array(dim, format="csc", dtype=int)
    else:
        E = np.eye(dim, dtype=int)

    return E


def op_Sx(S: float) -> np.ndarray | sp.csc_array:
    """
    Generate the Cartesian spin operator ``Sx``.

    Usage: ``op_Sx(S)``.

    Parameters
    ----------
    S : float
        Spin quantum number.

    Returns
    -------
    Sx : ndarray or csc_array
        Cartesian x-component spin operator.
    """

    # Combine the ladder operators into the x component.
    Sx = 1 / 2 * (op_Sp(S) + op_Sm(S))

    return Sx


def op_Sy(S: float) -> np.ndarray | sp.csc_array:
    """
    Generate the Cartesian spin operator ``Sy``.

    Usage: ``op_Sy(S)``.

    Parameters
    ----------
    S : float
        Spin quantum number.

    Returns
    -------
    Sy : ndarray or csc_array
        Cartesian y-component spin operator.
    """

    # Combine the ladder operators into the y component.
    Sy = 1 / (2j) * (op_Sp(S) - op_Sm(S))

    return Sy


def op_Sz(S: float) -> np.ndarray | sp.csc_array:
    """
    Generate the Cartesian spin operator ``Sz``.

    Usage: ``op_Sz(S)``.

    Parameters
    ----------
    S : float
        Spin quantum number.

    Returns
    -------
    Sz : ndarray or csc_array
        Cartesian z-component spin operator.
    """

    # Enumerate the magnetic quantum numbers from ``S`` down to ``-S``.
    m = -np.arange(-S, S + 1)

    # Allocate mutable storage for the diagonal operator.
    if parameters.sparse_operator:
        Sz = sp.lil_array((len(m), len(m)), dtype=float)
    else:
        Sz = np.zeros((len(m), len(m)), dtype=float)

    # Insert the magnetic quantum numbers onto the diagonal.
    for i, m_i in enumerate(m):
        Sz[i, i] = m_i

    # Return the operator in the configured output format.
    return Sz.tocsc() if parameters.sparse_operator else Sz


def op_Sp(S: float) -> np.ndarray | sp.csc_array:
    """
    Generate the spin-raising operator.

    Usage: ``op_Sp(S)``.

    Parameters
    ----------
    S : float
        Spin quantum number.

    Returns
    -------
    Sp : ndarray or csc_array
        Spin-raising operator.
    """

    # Enumerate the magnetic quantum numbers in ascending order.
    m = np.arange(-S, S + 1)

    # Allocate mutable storage for the off-diagonal operator.
    if parameters.sparse_operator:
        Sp = sp.lil_array((len(m), len(m)), dtype=float)
    else:
        Sp = np.zeros((len(m), len(m)), dtype=float)

    # Populate the non-zero elements generated by one raising step.
    for i in range(len(m) - 1):
        Sp[i, i + 1] = np.sqrt(S * (S + 1) - m[i] * (m[i] + 1))

    # Return the operator in the configured output format.
    return Sp.tocsc() if parameters.sparse_operator else Sp


def op_Sm(S: float) -> np.ndarray | sp.csc_array:
    """
    Generate the spin-lowering operator.

    Usage: ``op_Sm(S)``.

    Parameters
    ----------
    S : float
        Spin quantum number.

    Returns
    -------
    Sm : ndarray or csc_array
        Spin-lowering operator.
    """

    # Enumerate the magnetic quantum numbers in ascending order.
    m = np.arange(-S, S + 1)

    # Allocate mutable storage for the off-diagonal operator.
    if parameters.sparse_operator:
        Sm = sp.lil_array((len(m), len(m)), dtype=complex)
    else:
        Sm = np.zeros((len(m), len(m)), dtype=complex)

    # Populate the non-zero elements generated by one lowering step.
    for i in range(1, len(m)):
        Sm[i, i - 1] = np.sqrt(S * (S + 1) - m[i] * (m[i] - 1))

    # Return the operator in the configured output format.
    return Sm.tocsc() if parameters.sparse_operator else Sm


@lru_cache(maxsize=1024)
def _op_T(
    S: float,
    l: int,
    q: int,
    sparse: bool,
) -> np.ndarray | sp.csc_array:
    """
    Construct a cached single-spin irreducible spherical tensor operator.

    Usage: ``_op_T(S, l, q, sparse)``.

    Parameters
    ----------
    S : float
        Spin quantum number.
    l : int
        Tensor rank.
    q : int
        Tensor projection.
    sparse : bool
        Whether sparse operators should be returned.

    Returns
    -------
    T : ndarray or csc_array
        Cached spherical tensor operator in the requested storage format.
    """

    # Start from the maximum-projection tensor component ``T_l^l``.
    if sparse:
        T = (-1) ** l * 2 ** (-l / 2) * sp.linalg.matrix_power(op_Sp(S), l)
    else:
        T = (-1) ** l * 2 ** (-l / 2) * np.linalg.matrix_power(op_Sp(S), l)

    # Lower the projection stepwise until the requested value is reached.
    for i in range(l - q):
        current_q = l - i
        T = comm(op_Sm(S), T) / np.sqrt(
            l * (l + 1) - current_q * (current_q - 1)
        )

    return T


def op_T(S: float, l: int, q: int) -> np.ndarray | sp.csc_array:
    """
    Generate a single-spin irreducible spherical tensor operator.

    Usage: ``op_T(S, l, q)``.

    The operator is constructed by sequentially lowering the maximum-projection
    tensor. The implementation follows Kuprov, *Spin: From Basic Symmetries to
    Quantum Optimal Control* (2023), p. 94.

    Parameters
    ----------
    S : float
        Spin quantum number.
    l : int
        Tensor rank.
    q : int
        Tensor projection.

    Returns
    -------
    T : ndarray or csc_array
        Spherical tensor operator.
    """

    # Copy the cached tensor so that callers may modify their local result.
    T = _op_T(S, l, q, parameters.sparse_operator).copy()

    return T


def op_T_coupled(
    l: int,
    q: int,
    l1: int,
    s1: float,
    l2: int,
    s2: float,
) -> np.ndarray | sp.csc_array:
    """
    Construct a coupled irreducible spherical tensor for two spins.

    Usage: ``op_T_coupled(l, q, l1, s1, l2, s2)``.

    Parameters
    ----------
    l : int
        Rank of the coupled tensor.
    q : int
        Projection of the coupled tensor.
    l1 : int
        Rank of the first single-spin tensor.
    s1 : float
        Spin quantum number of the first spin.
    l2 : int
        Rank of the second single-spin tensor.
    s2 : float
        Spin quantum number of the second spin.

    Returns
    -------
    T : ndarray or csc_array
        Coupled spherical tensor operator of rank ``l`` and projection ``q``.
    """

    # Determine the composite Hilbert-space dimension.
    dim = int((2 * s1 + 1) * (2 * s2 + 1))

    # Allocate the accumulator for the coupled tensor.
    if parameters.sparse_operator:
        T = sp.csc_array((dim, dim), dtype=float)
    else:
        T = np.zeros((dim, dim), dtype=float)

    # Sum all Clebsch-Gordan-weighted tensor products.
    for q1 in range(-l1, l1 + 1):
        for q2 in range(-l2, l2 + 1):
            coefficient = CG_coeff(l1, q1, l2, q2, l, q)
            if parameters.sparse_operator:
                T = T + coefficient * sp.kron(
                    op_T(s1, l1, q1),
                    op_T(s2, l2, q2),
                    format="csc",
                )
            else:
                T = T + coefficient * np.kron(
                    op_T(s1, l1, q1),
                    op_T(s2, l2, q2),
                )

    return T


def op_prod(
    op_def: np.ndarray,
    spins: np.ndarray,
    include_unit: bool=True,
) -> np.ndarray | sp.csc_array:
    """
    Generate a many-spin product operator in the Zeeman eigenbasis.

    Usage: ``op_prod(op_def, spins, include_unit=True)``.

    Parameters
    ----------
    op_def : ndarray
        Integer definition of the product operator. For example,
        ``np.array([0, 2, 0, 1])`` corresponds to ``E*T_10*E*T_11``. The
        indices satisfy ``N = l**2 + l - q``.
    spins : ndarray
        Spin quantum numbers. The array length must match ``op_def``.
    include_unit : bool, default=True
        If ``False``, unit operators are omitted from the Kronecker product.

    Returns
    -------
    op : ndarray or csc_array
        Product operator in the Zeeman eigenbasis.
    """

    # Normalise the inputs to NumPy arrays.
    op_def = np.asarray(op_def)
    spins = np.asarray(spins)

    # Start from the scalar identity for iterative Kronecker products.
    if parameters.sparse_operator:
        op = sp.csc_array([[1]], dtype=float)
    else:
        op = np.array([[1]], dtype=float)

    # Append each requested single-spin tensor to the product operator.
    for spin, oper in zip(spins, op_def):
        if include_unit or oper != 0:
            l, q = idx_to_lq(oper)
            if parameters.sparse_operator:
                op = sp.kron(op, op_T(spin, l, q), format="csc")
            else:
                op = np.kron(op, op_T(spin, l, q))

    return op


def op_from_string(
    spins: np.ndarray,
    operator: str,
) -> np.ndarray | sp.csc_array:
    """
    Generate a Hilbert-space operator from a user-defined operator string.

    Usage: ``op_from_string(spins, operator)``.

    Parameters
    ----------
    spins : ndarray
        One-dimensional array of spin quantum numbers.
    operator : str
        Operator definition string. The supported syntax is summarised below:

        - Cartesian and ladder operators: ``I(component,index)`` or
          ``I(component)``. Examples:

          - ``I(x,4)`` creates the x-operator for the spin at index 4.
          - ``I(x)`` creates the x-operator for all spins.

        - Spherical tensor operators: ``T(l,q,index)`` or ``T(l,q)``.
          Examples:

          - ``T(1,-1,3)`` creates the operator with ``l=1`` and ``q=-1``
            for the spin at index 3.
          - ``T(1,-1)`` creates the operator with ``l=1`` and ``q=-1``
            for all spins.

        - Product operators are written with ``*`` between the single-spin
          operators, for example ``I(z,0) * I(z,1)``.
        - Sums of operators are written with ``+`` between the terms, for
          example ``I(x,0) + I(x,1)``.
        - Unit operators are ignored in the input, so ``E * I(z,1)`` and
          ``I(z,1)`` are interpreted identically.

        An empty string is interpreted as the unit operator. Whitespace is
        ignored, and indexing starts from zero.

    Returns
    -------
    op : ndarray or csc_array
        Requested operator in Hilbert space.
    """

    # Extract the size of the spin system from the spin quantum numbers.
    nspins = spins.shape[0]
    dim = int(np.prod(2 * spins + 1))

    # Allocate the operator accumulator in the configured storage format.
    if parameters.sparse_operator:
        op = sp.csc_array((dim, dim), dtype=float)
    else:
        op = np.zeros((dim, dim), dtype=float)

    # Parse the string into basis operators and their prefactors.
    op_defs, coeffs = parse_operator_string(operator, nspins)

    # Sum the parsed contributions into the final operator.
    for op_def, coeff in zip(op_defs, coeffs):
        op = op + coeff * op_prod(op_def, spins, include_unit=True)

    return op


def operator(
    spin_system: SpinSystem,
    operator: str | list | np.ndarray | tuple,
) -> np.ndarray | sp.csc_array:
    """
    Generate a Hilbert-space operator for a spin system.

    Usage: ``operator(spin_system, operator)``.

    The operator may be specified using either of the two approaches below:

    - A string. Example: ``I(z,0) * I(z,1)``.
    - A one-dimensional array of integers. Example: ``[2, 2]``.

    For string input, the supported syntax is as follows:

    - Cartesian and ladder operators: ``I(component,index)`` or
      ``I(component)``, with indexing starting from zero. Examples:

      - ``I(x,4)`` creates the x-operator for the spin at index 4.
      - ``I(x)`` creates the x-operator for all spins.

    - Spherical tensor operators: ``T(l,q,index)`` or ``T(l,q)``.
      Examples:

      - ``T(1,-1,3)`` creates the operator with ``l=1`` and ``q=-1`` for
        the spin at index 3.
      - ``T(1,-1)`` creates the operator with ``l=1`` and ``q=-1`` for all
        spins.

    - Product operators are written with ``*`` between the single-spin
      operators, for example ``I(z,0) * I(z,1)``.
    - Sums of operators are written with ``+`` between the terms, for
      example ``I(x,0) + I(x,1)``.
    - Unit operators are ignored in the input, so ``E * I(z,1)`` and
      ``I(z,1)`` are interpreted identically.

    An empty operator string is interpreted as the unit operator, and all
    whitespace is ignored.

    For array input, each spin is assigned an integer ``N`` that corresponds
    to a single-spin irreducible spherical tensor with rank ``l`` and
    projection ``q`` according to ``N = l**2 + l - q``.

    Parameters
    ----------
    spin_system : SpinSystem
        Spin system for which the operator is generated.
    operator : str or list or ndarray or tuple
        Operator specification in string or array form.

    Returns
    -------
    op : ndarray or csc_array
        Requested operator in Hilbert space.

    Raises
    ------
    ValueError
        Raised if the array input is not one-dimensional, has an incompatible
        length, or if the input type is unsupported.
    """

    # Parse string input with the operator-string helper.
    if isinstance(operator, str):
        op = op_from_string(
            spins=spin_system.spins,
            operator=operator,
        )

    # Parse array-like input as an explicit product-operator definition.
    elif isinstance(operator, (list, np.ndarray, tuple)):
        operator = np.asarray(operator)
        if operator.ndim != 1:
            raise ValueError("The input array must be one-dimensional.")
        if operator.shape[0] != spin_system.nspins:
            raise ValueError(
                "Length of the operator array must match the number of spins."
            )
        op = op_prod(
            spins=spin_system.spins,
            op_def=operator,
            include_unit=True,
        )

    # Reject unsupported input types explicitly.
    else:
        raise ValueError("Invalid input type for 'operator'.")

    return op


def clear_cache_op_T() -> None:
    """
    Clear the internal cache used by ``_op_T``.

    Usage: ``clear_cache_op_T()``.
    """

    # Remove all cached tensor operators.
    _op_T.cache_clear()