"""
Spin-operator construction utilities for Hilbert-space calculations.

The module provides single-spin Cartesian, ladder, and spherical tensor
operators together with helpers for assembling many-spin product operators.
"""

from __future__ import annotations

from functools import lru_cache
from typing import TYPE_CHECKING

import numpy as np
import scipy.sparse as sp

from spinguin._core._la import CG_coeff, comm
from spinguin._core._parameters import parameters
from spinguin._core._utils import idx_to_lq, parse_operator_string

if TYPE_CHECKING:
    from spinguin._core._spin_system import SpinSystem


def op_E(S: float) -> np.ndarray | sp.csc_array:
    """
    Generate the unit operator for a single spin.

    Parameters
    ----------
    S : float
        Spin quantum number.

    Returns
    -------
    E : ndarray or csc_array
        Unit operator of dimension ``2*S + 1`` in the configured storage
        format.
    """

    # Determine the Hilbert-space dimension of the spin.
    dim = int(2 * S + 1)

    # Allocate the identity matrix in the requested storage format.
    if parameters.sparse_operator:
        E = sp.eye_array(dim, format="csc", dtype=int)
    else:
        E = np.eye(dim, dtype=int)

    return E


def op_Sx(S: float) -> np.ndarray | sp.csc_array:
    """
    Generate the Cartesian spin operator ``Sx``.

    Parameters
    ----------
    S : float
        Spin quantum number.

    Returns
    -------
    Sx : ndarray or csc_array
        Cartesian x-component spin operator.
    """

    # Combine the ladder operators into the x component.
    Sx = 1 / 2 * (op_Sp(S) + op_Sm(S))

    return Sx


def op_Sy(S: float) -> np.ndarray | sp.csc_array:
    """
    Generate the Cartesian spin operator ``Sy``.

    Parameters
    ----------
    S : float
        Spin quantum number.

    Returns
    -------
    Sy : ndarray or csc_array
        Cartesian y-component spin operator.
    """

    # Combine the ladder operators into the y component.
    Sy = 1 / (2j) * (op_Sp(S) - op_Sm(S))

    return Sy


def op_Sz(S: float) -> np.ndarray | sp.csc_array:
    """
    Generate the Cartesian spin operator ``Sz``.

    Parameters
    ----------
    S : float
        Spin quantum number.

    Returns
    -------
    Sz : ndarray or csc_array
        Cartesian z-component spin operator.
    """

    # Enumerate the magnetic quantum numbers from ``S`` down to ``-S``.
    m = -np.arange(-S, S + 1)

    # Allocate mutable storage for the diagonal operator.
    if parameters.sparse_operator:
        Sz = sp.lil_array((len(m), len(m)), dtype=float)
    else:
        Sz = np.zeros((len(m), len(m)), dtype=float)

    # Insert the magnetic quantum numbers onto the diagonal.
    for i, m_i in enumerate(m):
        Sz[i, i] = m_i

    # Return the operator in the configured output format.
    return Sz.tocsc() if parameters.sparse_operator else Sz


def op_Sp(S: float) -> np.ndarray | sp.csc_array:
    """
    Generate the spin-raising operator.

    Parameters
    ----------
    S : float
        Spin quantum number.

    Returns
    -------
    Sp : ndarray or csc_array
        Spin-raising operator.
    """

    # Enumerate the magnetic quantum numbers in ascending order.
    m = np.arange(-S, S + 1)

    # Allocate mutable storage for the off-diagonal operator.
    if parameters.sparse_operator:
        Sp = sp.lil_array((len(m), len(m)), dtype=float)
    else:
        Sp = np.zeros((len(m), len(m)), dtype=float)

    # Populate the non-zero elements generated by one raising step.
    for i in range(len(m) - 1):
        Sp[i, i + 1] = np.sqrt(S * (S + 1) - m[i] * (m[i] + 1))

    # Return the operator in the configured output format.
    return Sp.tocsc() if parameters.sparse_operator else Sp


def op_Sm(S: float) -> np.ndarray | sp.csc_array:
    """
    Generate the spin-lowering operator.

    Parameters
    ----------
    S : float
        Spin quantum number.

    Returns
    -------
    Sm : ndarray or csc_array
        Spin-lowering operator.
    """

    # Enumerate the magnetic quantum numbers in ascending order.
    m = np.arange(-S, S + 1)

    # Allocate mutable storage for the off-diagonal operator.
    if parameters.sparse_operator:
        Sm = sp.lil_array((len(m), len(m)), dtype=complex)
    else:
        Sm = np.zeros((len(m), len(m)), dtype=complex)

    # Populate the non-zero elements generated by one lowering step.
    for i in range(1, len(m)):
        Sm[i, i - 1] = np.sqrt(S * (S + 1) - m[i] * (m[i] - 1))

    # Return the operator in the configured output format.
    return Sm.tocsc() if parameters.sparse_operator else Sm


@lru_cache(maxsize=1024)
def _op_T(
    S: float,
    l: int,
    q: int,
    sparse: bool,
) -> np.ndarray | sp.csc_array:
    """
    Construct a cached single-spin irreducible spherical tensor operator.

    Parameters
    ----------
    S : float
        Spin quantum number.
    l : int
        Tensor rank.
    q : int
        Tensor projection.
    sparse : bool
        Whether sparse operators should be returned.

    Returns
    -------
    T : ndarray or csc_array
        Cached spherical tensor operator in the requested storage format.
    """

    # Start from the maximum-projection tensor component ``T_l^l``.
    if sparse:
        T = (-1) ** l * 2 ** (-l / 2) * sp.linalg.matrix_power(op_Sp(S), l)
    else:
        T = (-1) ** l * 2 ** (-l / 2) * np.linalg.matrix_power(op_Sp(S), l)

    # Lower the projection stepwise until the requested value is reached.
    for i in range(l - q):
        current_q = l - i
        T = comm(op_Sm(S), T) / np.sqrt(
            l * (l + 1) - current_q * (current_q - 1)
        )

    return T


def op_T(S: float, l: int, q: int) -> np.ndarray | sp.csc_array:
    """
    Generate a single-spin irreducible spherical tensor operator.

    The operator is constructed by sequentially lowering the maximum-projection
    tensor. The implementation follows Kuprov, *Spin: From Basic Symmetries to
    Quantum Optimal Control* (2023), p. 94.

    Parameters
    ----------
    S : float
        Spin quantum number.
    l : int
        Tensor rank.
    q : int
        Tensor projection.

    Returns
    -------
    T : ndarray or csc_array
        Spherical tensor operator.
    """

    # Copy the cached tensor so that callers may modify their local result.
    T = _op_T(S, l, q, parameters.sparse_operator).copy()

    return T


def op_T_coupled(
    l: int,
    q: int,
    l1: int,
    s1: float,
    l2: int,
    s2: float,
) -> np.ndarray | sp.csc_array:
    """
    Construct a coupled irreducible spherical tensor for two spins.

    Parameters
    ----------
    l : int
        Rank of the coupled tensor.
    q : int
        Projection of the coupled tensor.
    l1 : int
        Rank of the first single-spin tensor.
    s1 : float
        Spin quantum number of the first spin.
    l2 : int
        Rank of the second single-spin tensor.
    s2 : float
        Spin quantum number of the second spin.

    Returns
    -------
    T : ndarray or csc_array
        Coupled spherical tensor operator of rank ``l`` and projection ``q``.
    """

    # Determine the composite Hilbert-space dimension.
    dim = int((2 * s1 + 1) * (2 * s2 + 1))

    # Allocate the accumulator for the coupled tensor.
    if parameters.sparse_operator:
        T = sp.csc_array((dim, dim), dtype=float)
    else:
        T = np.zeros((dim, dim), dtype=float)

    # Sum all Clebsch-Gordan-weighted tensor products.
    for q1 in range(-l1, l1 + 1):
        for q2 in range(-l2, l2 + 1):
            coefficient = CG_coeff(l1, q1, l2, q2, l, q)
            if parameters.sparse_operator:
                T = T + coefficient * sp.kron(
                    op_T(s1, l1, q1),
                    op_T(s2, l2, q2),
                    format="csc",
                )
            else:
                T = T + coefficient * np.kron(
                    op_T(s1, l1, q1),
                    op_T(s2, l2, q2),
                )

    return T


def op_prod(
    op_def: np.ndarray,
    spins: np.ndarray,
    include_unit: bool=True,
) -> np.ndarray | sp.csc_array:
    """
    Generate a many-spin product operator in the Zeeman eigenbasis.

    Parameters
    ----------
    op_def : ndarray
        Integer definition of the product operator. For example,
        ``np.array([0, 2, 0, 1])`` corresponds to ``E*T_10*E*T_11``. The
        indices satisfy ``N = l**2 + l - q``.
    spins : ndarray
        Spin quantum numbers. The array length must match ``op_def``.
    include_unit : bool, default=True
        If ``False``, unit operators are omitted from the Kronecker product.

    Returns
    -------
    op : ndarray or csc_array
        Product operator in the Zeeman eigenbasis.
    """

    # Normalise the inputs to NumPy arrays.
    op_def = np.asarray(op_def)
    spins = np.asarray(spins)

    # Start from the scalar identity for iterative Kronecker products.
    if parameters.sparse_operator:
        op = sp.csc_array([[1]], dtype=float)
    else:
        op = np.array([[1]], dtype=float)

    # Append each requested single-spin tensor to the product operator.
    for spin, oper in zip(spins, op_def):
        if include_unit or oper != 0:
            l, q = idx_to_lq(oper)
            if parameters.sparse_operator:
                op = sp.kron(op, op_T(spin, l, q), format="csc")
            else:
                op = np.kron(op, op_T(spin, l, q))

    return op


def _op_from_string(
    spin_system: SpinSystem,
    operator: str | list | np.ndarray | tuple,
) -> np.ndarray | sp.csc_array:
    """
    Generate a Hilbert-space operator from a user-defined operator string.

    Parameters
    ----------
    spin_system : SpinSystem
        Spin system for which the operator is going to be generated.
    operator : str or list or ndarray or tuple
        Defines the operator to be generated.

        **The operator can be defined with two different approaches:**

        - A string. Example: ``I(z, 0) * I(z, 1)``.
        - An array of integers. Example: ``[2, 2]``.

        **The operator string must follow the rules below:**

        - Cartesian or ladder operator at specific index, for all spins, or for
          all spins of the same isotope::

            operator = "I(component, index)"
            operator = "I(component)"
            operator = "I(component, isotope)"

        - Spherical tensor operator at specific index, for all spins, or for
          all spins of the same isotope::

            operator = "T(l, q, index)"
            operator = "T(l, q)"
            operator = "T(l, q, isotope)"

        - Product operators::

            operator = "I(component1, index1) * I(component2, index2)"

        - Sum of operators::

            operator = "I(component1, index1) + I(component2, index2)"

        - Unit operators are ignored in the input. These are identical::

            operator = "E * I(component, index)"
            operator = "I(component, index)"

        Special case: An empty ``operator`` string is considered as the unit
        operator.

        Whitespace will be ignored in the input.

        **The array input is defined as follows:**

        - Each spin is given an integer *N* in the array.
        - Each integer corresponds to a spherical tensor operator of rank *l*
          and projection *q*: *N* = *l*^2 + *l* - *q*

        Note that indexing starts from 0.

    Returns
    -------
    op : ndarray or csc_array
        Requested operator in Hilbert space.
    """

    # Allocate the operator accumulator in the configured storage format.
    dim = int(np.prod(spin_system.mults))
    if parameters.sparse_operator:
        op = sp.csc_array((dim, dim), dtype=float)
    else:
        op = np.zeros((dim, dim), dtype=float)

    # Parse the string into basis operators and their prefactors.
    op_defs, coeffs = parse_operator_string(spin_system, operator)

    # Sum the parsed contributions into the final operator.
    for op_def, coeff in zip(op_defs, coeffs):
        op = op + coeff * op_prod(op_def, spin_system.spins, include_unit=True)

    return op


def operator(
    spin_system: SpinSystem,
    operator: str | list | np.ndarray | tuple,
) -> np.ndarray | sp.csc_array:
    """
    Generate a Hilbert-space operator for a spin system.

    Parameters
    ----------
    spin_system : SpinSystem
        Spin system for which the operator is going to be generated.
    operator : str or list or ndarray or tuple
        Defines the operator to be generated.

        **The operator can be defined with two different approaches:**

        - A string. Example: ``I(z, 0) * I(z, 1)``.
        - An array of integers. Example: ``[2, 2]``.

        **The operator string must follow the rules below:**

        - Cartesian or ladder operator at specific index, for all spins, or for
          all spins of the same isotope::

            operator = "I(component, index)"
            operator = "I(component)"
            operator = "I(component, isotope)"

        - Spherical tensor operator at specific index, for all spins, or for
          all spins of the same isotope::

            operator = "T(l, q, index)"
            operator = "T(l, q)"
            operator = "T(l, q, isotope)"

        - Product operators::

            operator = "I(component1, index1) * I(component2, index2)"

        - Sum of operators::

            operator = "I(component1, index1) + I(component2, index2)"

        - Unit operators are ignored in the input. These are identical::

            operator = "E * I(component, index)"
            operator = "I(component, index)"

        Special case: An empty ``operator`` string is considered as the unit
        operator.

        Whitespace will be ignored in the input.

        **The array input is defined as follows:**

        - Each spin is given an integer *N* in the array.
        - Each integer corresponds to a spherical tensor operator of rank *l*
          and projection *q*: *N* = *l*^2 + *l* - *q*

        Note that indexing starts from 0.

    Returns
    -------
    op : ndarray or csc_array
        Requested operator in Hilbert space.

    Raises
    ------
    ValueError
        Raised if the array input is not one-dimensional, has an incompatible
        length, or if the input type is unsupported.
    """

    # Parse string input with the operator-string helper.
    if isinstance(operator, str):
        op = _op_from_string(spin_system, operator)

    # Parse array-like input as an explicit product-operator definition.
    elif isinstance(operator, (list, np.ndarray, tuple)):
        operator = np.asarray(operator)
        if operator.ndim != 1:
            raise ValueError("The input array must be one-dimensional.")
        if operator.shape[0] != spin_system.nspins:
            raise ValueError(
                "Length of the operator array must match the number of spins."
            )
        op = op_prod(
            spins=spin_system.spins,
            op_def=operator,
            include_unit=True,
        )

    # Reject unsupported input types explicitly.
    else:
        raise ValueError("Invalid input type for 'operator'.")

    return op


def clear_cache_op_T() -> None:
    """
    Clear the internal cache used by ``_op_T``.
    """

    # Remove all cached tensor operators.
    _op_T.cache_clear()